# DEPLOYMENT
apiVersion: apps/v1 #nombre declarado de la app
kind: Deployment
metadata:
  name: backend-despachos
spec: #comienza la configuración del contenedor
  replicas: 2
  selector:
    matchLabels:
      app: backend-despachos
  template:
    metadata:
      labels:
        app: backend-despachos
    spec:
      containers:
        - name: backend-despachos
          image: 654654373802.dkr.ecr.us-east-1.amazonaws.com/innovatech-ms-despachos:latest #debería ser el nombre de una imagen que ya existe
          imagePullPolicy: Always #no intentes descargar la imagen desde docker hub
          ports:
            - containerPort: 8082
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql:3306/innovatech
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              value: root


---
# SERVICE
apiVersion: v1
kind: Service
metadata:
  name: backend-despachos
spec:
  selector:
    app: backend-despachos
  ports:
    - port: 8082
      targetPort: 8082
      nodePort: 30082
  type: NodePort
  
